name: Basic PR Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  basic_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Simple check
        run: echo "This is a basic check. PR workflow passed!"
